# Generated by Django 4.2.3 on 2023-07-05 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="What's your name?")),
                ('email', models.CharField(max_length=255, verbose_name="What's your email address?")),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name="What's your phone number?")),
                ('state', models.CharField(max_length=255, verbose_name="What's your state of residence?")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='waitlist.userdata')),
            ],
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userphone',
            name='email',
        ),
        migrations.DeleteModel(
            name='UserEmail',
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
        migrations.DeleteModel(
            name='UserName',
        ),
        migrations.DeleteModel(
            name='UserPhone',
        ),
    ]
